# This is a basic workflow to help you get started with Actions

name: Generate Release EXE

# Controls when the workflow will run
on:
  push:
    tags:
      - v.**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
        architecture: x64
    - run: |
        pip3 install -r requirements.txt pyinstaller
        pyinstaller .\main.spec
        ls
    # - name: Create Github Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     commit: ${{ github.sha }}
    #     tag: ${{ env.app_tag }}
    #     artifacts: "build/app/outputs/flutter-apk/app-release.apk"

    # - name: Save APK to Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: APK
    #     path: build/app/outputs/flutter-apk/app-release.apk